#!/usr/bin/env bash
# This script will generate secrets for use in both the Netbox and AWX installs

# If you wish to use your own secrets, then a secrets.env file can be provided instead 
# of using this file, or the prompts can be followed. The secrets.env file must match 
# what is set in this script

# Change to current wd
set -euo pipefail
cd "$(dirname "$0")"

# Random string generator
# Usage:
#   random_string [length]
# Default length is 32
random_string() { 
    local length="${1:-32}" 
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$length" 
    echo 
}

# Resolve secret
# Usage:
#   resolve_secret [var_name] [length]
# Default length is 32
# If no [var_name] is provided, a random string of [length] will be generated
resolve_secret() {
    local var_name="$1"
    local length="$2"
    local default_val
    default_val="$(random_string "$length")"

    if [[ -t 0 ]]; then
        local input
        read -r -p "Enter value for $var_name [press ENTER to auto-generate]: " input >&2
        printf '%s' "${input:-$default_val}"
    else
        printf '%s' "$default_val"
    fi
}

NETBOX_ADMIN_PASSWORD="$(resolve_secret NETBOX_ADMIN_PASSWORD 16)"
NETBOX_SECRET_KEY="$(random_string 50)"
NETBOX_PG_PASSWORD="$(resolve_secret NETBOX_PG_PASSWORD 16)"
NETBOX_REDIS_PASSWORD="$(resolve_secret NETBOX_REDIS_PASSWORD 16)"

AWX_ADMIN_PASSWORD="$(resolve_secret AWX_ADMIN_PASSWORD 16)"
AWX_SECRET_KEY="$(random_string 50)"

DEVICE_USERNANME="$(resolve_secret DEVICE_USERNANME 16)"
DEVICE_PASSWORD="$(resolve_secret DEVICE_PASSWORD 16)"

# Generate secrets.env file
cat > secrets.env <<EOF
# Generated by gen-secrets.sh
NETBOX_ADMIN_PASSWORD=$NETBOX_ADMIN_PASSWORD
NETBOX_SECRET_KEY=$NETBOX_SECRET_KEY
NETBOX_PG_PASSWORD=$NETBOX_PG_PASSWORD
NETBOX_REDIS_PASSWORD=$NETBOX_REDIS_PASSWORD

AWX_ADMIN_PASSWORD=$AWX_ADMIN_PASSWORD
AWX_SECRET_KEY=$AWX_SECRET_KEY

DEVICE_USERNANME=$DEVICE_USERNANME
DEVICE_PASSWORD=$DEVICE_PASSWORD
EOF

echo "secrets.env generated successfully"